name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: set_var
        run: |
          content=`cat package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=nodePackage::$content"
      - name: Compile .ts files to .js with tsc
        run: yarn && yarn tsc && ls -la
      - name: Build the Docker image
        run: |
          tag=${{ fromJson(steps.set_var.outputs.nodePackage).version }}
          docker build . --file Dockerfile --tag ghcr.io/randy-halim/overlake-discord:$tag
      - name: Login to ghcr.io (beta)
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Push to registry
        run: |
          tag=${{ fromJson(steps.set_var.outputs.nodePackage).version }}
          docker push ghcr.io/randy-halim/overlake-discord:latest:$tag
