name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nyaayaya/package-version@v1
        with:
          path: packages/discord/package.json
      - name: Compile .ts files to .js with tsc
        run: |
          cd packages/discord
          yarn
          yarn build
      - name: Build the Docker image
        working-directory: packages/discord
        run: "docker build . --file Dockerfile --tag ghcr.io/randy-halim/overlake-discord:${{ env.PACKAGE_VERSION }} --tag ghcr.io/randy-halim/overlake-discord:latest"
      - name: Login to ghcr.io (beta)
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Push to registry
        run: "docker push ghcr.io/randy-halim/overlake-discord"
