name: Discord Docker image CI/CD

on:
  push:
    branches:
      - master
      - "ci/**"
    paths:
      - .github/workflows/**
      - packages/discord/**

jobs:
  build-discord:
    runs-on: ubuntu-20.04
    name: "Build and Bundle"
    steps:
      - uses: actions/checkout@v2
      - name: Compile .ts source to .js with fuse-box
        run: |
          cd packages/discord
          yarn
          yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: js-bundle
          path: packages/discord/build
      - uses: actions/upload-artifact@v2
        with:
          name: js-package
          path: packages/discord/package.json
  deploy-discord:
    needs: build-discord
    name: "Deploy Image to ghcr.io"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2 # download js-bundle and js-package
        id: download
        with:
          name: js-bundle
      - uses: actions/download-artifact@v2
        with:
          name: js-package
      - uses: nyaayaya/package-version@v1
      - name: List working directory
        run: ls -laR
      - name: Build the Docker image
        working-directory: "${{steps.download.outputs.download-path}}"
        run: "docker build . --file Dockerfile --tag ghcr.io/randy-halim/overlake-discord:${{ env.PACKAGE_VERSION }} --tag ghcr.io/randy-halim/overlake-discord:latest"
      - name: Login to ghcr.io (beta)
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Push to registry
        run: "docker push ghcr.io/randy-halim/overlake-discord"
