name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Declare version variable
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Compile .ts files to .js with tsc
        run: yarn && yarn tsc
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/randy-halim/overlake-discord:latest
      - name: Login to ghcr.io (beta)
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Push to registry
        run: docker push ghcr.io/randy-halim/overlake-discord:latest
