name: Unit Testing

on:
  push:
    branches:
      - master
      - "ci/**"
  pull_request:
    branches:
      - master

jobs:
  test-discord:
    runs-on: ubuntu-20.04
    name: "Unit Testing: Discord"
    steps:
      - uses: actions/checkout@v2
      - name: List working directory
        working-directory: packages/discord
        run: ls -laR
      - name: Install dependencies
        working-directory: packages/discord
        run: yarn
      - name: Run testing
        run: |
          ls -laR
          echo "Tests pass if test runner doesn't error"
          yarn test
